service: wlq-api-aws

# Expected env variables: see .env

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024

  # CloudWatch Logs role ARN must be set in account settings to enable logging
  # logs:
  #   websocket:
  #     level: INFO

  websocketApiName: websocket-chat-${self:provider.stage}
  websocketApiRouteSelectionExpression: $request.body.action

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    ROOM_TABLE_NAME: ${self:custom.roomTableName}
    ALLOW_ORIGIN: ${self:custom.httpOrigin}
    BROADCAST_TOPIC: $self:custom.{broadcastTopic}
    WEBSOCKET_ENDPOINT:
      Fn::Join:
        - ""
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem

        # - dynamodb:Scan
        # - dynamodb:UpdateItem

      Resource:
        - { "Fn::GetAtt": ["RoomTable", "Arn"] }
        - Fn::Join: ["/", [{ "Fn::GetAtt": ["RoomTable", "Arn"] }, "index/*"]]

    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        - Fn::Join:
            [
              "",
              [
                "arn:aws:sns:${self:provider.region}:",
                { "Ref": "AWS::AccountId" },
                ":${self:custom.broadcastTopic}",
              ],
            ]

plugins:
  - serverless-webpack

custom:
  hostedZoneId: ${env:HOSTED_ZONE_ID}
  siteName: ${env:API_DOMAIN}
  httpOrigin: https://${env:SITE_DOMAIN}
  acmCertificateArn: ${env:ACM_CERTIFICATE_ARN}
  roomTableName: ${self:service}-RoomTable-${self:provider.stage}
  broadcastTopic: "${self:service}-broadcast-${self:provider.stage}"
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

functions:
  getToken:
    handler: src/lambdas/getToken.handler
    events:
      - http:
          path: getToken
          origin: ${self:custom.httpOrigin}
          method: GET
          cors: true

  getRoom:
    handler: src/lambdas/getRoom.handler
    events:
      - http:
          path: getRoom
          origin: ${self:custom.httpOrigin}
          authorizer:
            name: authorize
            resultTtlInSeconds: 0
          method: POST
          cors: true

  createRoom:
    handler: src/lambdas/createRoom.handler
    events:
      - http:
          path: createRoom
          origin: ${self:custom.httpOrigin}
          authorizer:
            name: authorize
            resultTtlInSeconds: 0
          method: POST
          cors: true

  authorize:
    handler: src/lambdas/authorize.handler

  socketConnection:
    handler: src/lambdas/socketConnection.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

  joinRoom:
    handler: src/lambdas/joinRoom.handler
    events:
      - websocket:
          route: joinRoom

  startGame:
    handler: src/lambdas/startGame.handler
    events:
      - websocket:
          route: startGame

  answerQuestion:
    handler: src/lambdas/answerQuestion.handler
    events:
      - websocket:
          route: answerQuestion

  broadcastTopic:
    handler: src/lambdas/broadcastTopic.dispatch
    events:
      - sns:
          arn:
            Ref: BroadcastTopic
          topicName: ${self:custom.broadcastTopic}
          filterPolicy:
            action:
              - userJoined
              - userLeft
              - userAnswered

resources:
  Resources:
    BroadcastTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.broadcastTopic}

    WebsocketsApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: WebsocketsApi
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.action"

    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'${self:custom.httpOrigin}'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

    RoomTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.roomTableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: InverseIndex
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: PK
                KeyType: RANGE
            Projection:
              # TODO we could probably do with KEYS_ONLY
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

package:
  individually: true
  excludeDevDependencies: true
