service: wlq-api-aws

# Expected env variables:
# SITE_DOMAIN (sub)domain of the root service (static site - wql-app-aws)

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

plugins:
  - serverless-webpack

custom:
  hostedZoneId: ${env:HOSTED_ZONE_ID}
  siteName: ${env:API_DOMAIN}
  httpOrigin: https://${SITE_DOMAIN}
  acmCertificateArn: ${env:ACM_CERTIFICATE_ARN}
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

functions:
  getToken:
    handler: src/lambdas/getToken.handler
    events:
      - http:
          path: getToken
          origin: ${self:custom.httpOrigin}
          method: GET
          cors: true

  getRoom:
    handler: src/lambdas/getRoom.handler
    events:
      - http:
          path: getRoom
          origin: ${self:custom.httpOrigin}
          authorizer: authorize
          method: POST
          cors: true

  authorize:
    handler: src/lambdas/authorize.handler

package:
  individually: true
  excludeDevDependencies: true
