service: wlq-app-aws

# Expected env variables:
# HOSTED_ZONE_ID
# API_OCT_SECRET_KEY
# SITE_DOMAIN (sub)domain of the root service (static site - wql-app-aws)
# ACM_CERTIFICATE_ARN certificate ARN for given hosted zone

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-s3-deploy
  - serverless-plugin-scripts

custom:
  hostedZoneId: ${env:HOSTED_ZONE_ID}
  siteName: ${env:SITE_DOMAIN}
  acmCertificate: ${env:ACM_CERTIFICATE_ARN}

  scripts:
    hooks:
      "package:createDeploymentArtifacts": cd ../wlq-app && NEXT_TELEMETRY_DISABLED=1 yarn build:serverless

  cloudfrontInvalidate:
    distributionIdKey: "CloudFrontDistributionId"
    items:
      - "/*"

  assets:
    auto: true
    targets:
      - bucket: ${self:custom.siteName}
        empty: true

        files:
          - source: ../wlq-app/.next/serverless/pages/
            globs: "**/*.html"

          - source: ../wlq-app/public/
            globs: "**/*"
            headers:
              CacheControl: max-age=86400

      - bucket: ${self:custom.siteName}
        prefix: _next/static
        files:
          - source: ../wlq-app/.next/static/
            globs: "**/*.js"
            headers:
              CacheControl: max-age=86400

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html

    StaticSiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::", { "Ref": "StaticSite" }, "/*"]]

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          PriceClass: PriceClass_100
          Origins:
            - DomainName: ${self:custom.siteName}.s3-website.eu-central-1.amazonaws.com
              ## An identifier for the origin which must be unique within the distribution
              Id: StaticSiteOrigin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
              ## In case you want to restrict the bucket access use S3OriginConfig and remove CustomOriginConfig
              # S3OriginConfig:
              #   OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
          Enabled: "true"

          Aliases:
            - ${self:custom.siteName}

          DefaultRootObject: index.html

          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 404
              ResponsePagePath: /404.html

          HttpVersion: http2

          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS

            ## The origin id defined above
            TargetOriginId: StaticSiteOrigin
            ## Defining if and how the QueryString and Cookies are forwarded to the origin which in this case is S3
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ## The protocol that users can use to access the files in the origin. To allow HTTP use `allow-all`
            ViewerProtocolPolicy: redirect-to-https

            Compress: true

          ViewerCertificate:
            AcmCertificateArn: ${self:custom.acmCertificate}
            SslSupportMethod: sni-only

    DNSRecords:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${self:custom.hostedZoneId}
        RecordSets:
          - Name: ${self:custom.siteName}
            Type: A
            AliasTarget:
              # For CloudFront, HostedZoneId is always Z2FDTNDATAQYW2, see:
              # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
              HostedZoneId: Z2FDTNDATAQYW2
              DNSName:
                "Fn::GetAtt": [CloudFrontDistribution, DomainName]

  Outputs:
    CloudFrontDistributionId:
      Description: Static site CloudFront distribution id
      Value:
        Ref: CloudFrontDistribution
