name: Verify wlq-app package

on:
  push:
    paths:
      - packages/wlq-app/*
      - .github/workflows/*
      - .eslintrc.json
      - tsconfig.json

jobs:
  verify_and_test:
    name: Lint and compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: yarn workspace @wlq/wlq-app verify:lint

      - name: Typescript check
        run: yarn workspace @wlq/wlq-app verify:tsc
