name: Verify wlq-core package

on:
  push:
    paths:
      - packages/*
      - .github/workflows/*
      - .eslintrc.json
      - tsconfig.json

jobs:
  verify_and_test:
    name: Lint, compile, test & coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install

      - name: Lint wlq-core
        run: yarn workspace @wlq/wlq-core verify:lint

      - name: Build wlq-core
        run: yarn workspace @wlq/wlq-core build

      - name: Test wlq-core
        run: yarn workspace @wlq/wlq-core test:coverage

      - name: Lint wlq-app
        run: yarn workspace @wlq/wlq-app verify:lint

      - name: Typescript wlq-app
        run: yarn workspace @wlq/wlq-app verify:tsc

      - name: Test wlq-app
        run: yarn workspace @wlq/wlq-app test:coverage

      - name: Lint wlq-api-aws
        run: yarn workspace @wlq/wlq-api-aws verify:lint

      - name: Typescript wlq-api-aws
        run: yarn workspace @wlq/wlq-api-aws verify:tsc

      # - name: Test wlq-api-aws
      #   run: yarn workspace @wlq/wlq-app test:coverage

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/wlq-core/coverage/lcov.info,./packages/wlq-app/coverage/lcov.info
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

